import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [input, setInput] = useState('Armoni Çikolata');

  const handleChange = (e) => {
    setInput(e.target.value)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Armoni Çikolata</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>
      <header className="w-full h-[60px] shadow-lg">
        <div className="container">
          <div className="w-full h-[60px] flex justify-center items-center">
            <Image src="/armonilogo3.jpg" alt="logo-armoni" width={90} height={50} priority objectFit='cover' className="rounded" />
          </div>
        </div>
      </header>
      <main className={styles.main}>
        <div className="flex justify-center">
          <input className="w-full h-10 mt-10 border-2 border-gray-800 rounded-lg px-3 focus:outline-hidden focus:border-gray-800"
            type="text" name="name" placeholder='Örneğin: Derya ve Kenan' onChange={(e) => handleChange(e)} />
        </div>
        <h1 className="font-['Amazon'] flex justify-center text-3xl mt-4">Lütfen Metin Giriniz</h1>
        <div className="flex justify-center m-10">
          <div className={styles.left}>
            <div className="flex">
              <div className={styles.fonts}>F1</div>
              <div className="font-['MonoType'] border-t-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
            <div className="flex">
              <div className={styles.fonts}>F2</div>
              <div className="font-['Amazon'] border-t-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts} border-b-2`}>F3</div>
              <div className="font-['Massillo'] border-t-2 border-b-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts} border-b-2`}>F4</div>
              <div className="font-['Angelina']  border-b-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts} border-b-2`}>F5</div>
              <div className="font-['Bellesa']  border-b-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts} border-b-2`}>F6</div>
              <div className="font-['Arthurdale']  border-b-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts} border-b-2`}>F7</div>
              <div className="font-['Agreable']  border-b-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts} border-b-2`}>F8</div>
              <div className="font-['Anydore']  border-b-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts} border-b-2`}>F9</div>
              <div className="font-['BrushScript']  border-b-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts} border-b-2`}>F10</div>
              <div className="font-['Harstmount']  border-b-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
          </div>
          <div className={styles.right}>

            <div className="flex">
              <div className={styles.fonts}>F11</div>
              <div className="font-['HaverinkScript'] border-t-2 border-r-2 border-gray-900 flex items-center w-[140px]  ">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts}`}>F12</div>
              <div className="border-t-2 border-r-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts} border-b-2`}>F13</div>
              <div className="font-['SavoyeLetPlain'] border-t-2 border-r-2 border-b-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts} border-b-2`}>F14</div>
              <div className="font-['CandleMustard'] border-r-2 border-b-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts} border-b-2`}>F15</div>
              <div className="font-['Snell'] border-r-2 border-b-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts} border-b-2`}>F16</div>
              <div className="font-['Humble'] border-r-2 border-b-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts} border-b-2`}>F17</div>
              <div className="font-['YouthLine'] border-r-2 border-b-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts} border-b-2`}>F18</div>
              <div className="font-['Gabriola'] border-r-2 border-b-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts} border-b-2`}>F19</div>
              <div className="font-['AmericanTypewriter'] border-r-2 border-b-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts} border-b-2`}>F20</div>
              <div className="font-['EMBASSYN'] border-r-2 border-b-2 border-gray-900 flex items-center w-[140px]">{input}</div>
            </div>
          </div>
        </div>
      </main>
      <footer className={styles.footer}>
        <Link href="https://l.instagram.com/?u=https%3A%2F%2Fwa.me%2F%2B905316096155%2F&e=ATOE6WyoSSo0uI-_LFswWWv-qEyTt1dGjWcma0ZybzvxMmKwokS8zA4F3bH9-HCCjDB7VYQWWYH1zTFeLGmiAA&s=1" passHref>
          <a className="absolute left-3 bottom-3">

            <Image src="/whatsapp.png" alt="logo-whatsapp" width={50} height={50} />
          </a>
        </Link>
      </footer>
    </div>
  )
}
