import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [input, setInput] = useState('Armoni Çikolata');

  const handleChange = (e) => {
    setInput(e.target.value)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Armoni Çikolata</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="flex justify-center">
          <input className="w-1/3 h-10 mt-10 border-2 border-gray-800 rounded-lg px-3 focus:outline-hidden focus:border-gray-800"
            type="text" name="name" placeholder='Metni giriniz...' onChange={(e) => handleChange(e)} />
        </div>
        <h1 className="flex justify-center text-3xl mt-4">Lütfen Font Seçiniz</h1>
        <div className="flex justify-center m-10">
          <div className={styles.left}>

            <div className="flex">
              <div className={styles.fonts}>F1</div>
              <div className="font-['MonoType'] p-4 border-t-2 border-gray-900 w-[200px] max-w-[300px]">{input}</div>
            </div>
            <div className="flex">
              <div className={styles.fonts}>F2</div>
              <div className="font-['Amazon']  p-4 border-t-2 border-gray-900 w-[200px]  max-w-[300px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts} border-b-2`}>F3</div>
              <div className="font-['Massillo'] p-4 border-t-2 border-b-2 border-gray-900 w-[200px]  max-w-[300px]">{input}</div>
            </div>
          </div>
          <div className={styles.right}>

            <div className="flex">
              <div className={styles.fonts}>F11</div>
              <div className="font-['HaverinkScript'] p-4 border-t-2 border-r-2 border-gray-900 w-[200px]  max-w-[300px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts}`}>F12</div>
              <div className="p-4 border-t-2 border-r-2 border-gray-900 w-[200px]  max-w-[300px]">{input}</div>
            </div>
            <div className="flex">
              <div className={`${styles.fonts} border-b-2`}>F13</div>
              <div className="font-['SavoyeLetPlain'] p-4 border-t-2 border-r-2 border-b-2 border-gray-900 w-[200px]  max-w-[300px]">{input}</div>
            </div>
          </div>


        </div>



      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
